name: Build My Demo App
on: 
  push:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  run-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
        # Available XCodes taken from https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11.0-Readme.md
        - xcode-version: 12.4
          device-destination: "name=iPhone 11 Pro Max"
          simulator-destination: "Any iOS Simulator Device"
        - xcode-version: 12.3
          device-destination: "name=iPhone 11 Pro Max"
          simulator-destination: "Any iOS Simulator Device"
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: gem install xcpretty
    - name: Select XCode
      uses: maxim-lobanov/setup-xcode@v1.2.1
      with:
        xcode-version: ${{ matrix.xcode-version }}
    - name: Build for iOS Simulator
      run:  |
        set -o pipefail && \
        xcodebuild ONLY_ACTIVE_ARCH=NO ARCHS_STANDARD="i386 x86_64" \
          -workspace "My Demo App.xcworkspace" -scheme "My Demo App" \
          -sdk iphonesimulator -destination "${{ matrix.simulator-destination }}" \
          -configuration Release -derivedDataPath build | xcpretty