name: Create Release for My Demo App
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
        # Available XCodes taken from https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11.0-Readme.md
        - xcode-version: 12.4
          destination: "name=iPhone 11 Pro Max"
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: gem install xcpretty
    - name: Select XCode
      uses: maxim-lobanov/setup-xcode@v1.2.1
      with:
        xcode-version: ${{ matrix.xcode-version }}
    - uses: yukiarrr/ios-build-action@v1.4.0
      with:
        workspace-path: My Demo App.xcworkspace
        project-path: My Demo App.xcodeproj
        scheme: My Demo App
        code-signing-identity: iOS Development
        export-method: development
        output-path: build/demo-app.ipa
        p12-base64: ${{ secrets.P12_BASE64 }}
        certificate-password: ${{ secrets.P12_PASSWORD }}
        mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        team-id: ${{ secrets.TEAM_ID }}
    - name: Print Build Folder
      run: ls -lsrt build/
        
