apiVersion: v1alpha
kind: xcuitest
sauce:
  region: us-west-1
  concurrency: 5
  metadata:
    name: Testing XCUITEST Support
    tags:
      - e2e
      - release team
      - other tag
  build: Release $CI_COMMIT_SHORT_SHA

xcuitest:
  app: MyDemoApp.ipa
  testApp: MyDemoAppUITests-Runner.app

suites:
  - name: "saucy xcuitest"
    devices:
      # If set, only device by ID will be queried.
      #- id: <rdc_device_id>
      - name: "iPhone.*"
        # platformVersion: "14.6"
        options:
          # If set, only devices with a SIM card will be queried.
          carrierConnectivity: false
          # Possible values [ANY,PHONE,TABLET]
          deviceType: PHONE
          # If set, only private devices will be queried.
          private: false
      - name: "iPhone.*"
        # platformVersion: "14.6"
        options:
          # If set, only devices with a SIM card will be queried.
          carrierConnectivity: false
          # Possible values [ANY,PHONE,TABLET]
          deviceType: PHONE
          # If set, only private devices will be queried.
          private: false
      - name: "iPhone.*"
        # platformVersion: "14.6"
        options:
          # If set, only devices with a SIM card will be queried.
          carrierConnectivity: false
          # Possible values [ANY,PHONE,TABLET]
          deviceType: PHONE
          # If set, only private devices will be queried.
          private: false
      - name: "iPhone.*"
        # platformVersion: "14.6"
        options:
          # If set, only devices with a SIM card will be queried.
          carrierConnectivity: false
          # Possible values [ANY,PHONE,TABLET]
          deviceType: PHONE
          # If set, only private devices will be queried.
          private: false
      - name: "iPhone.*"
        # platformVersion: "14.6"
        options:
          # If set, only devices with a SIM card will be queried.
          carrierConnectivity: false
          # Possible values [ANY,PHONE,TABLET]
          deviceType: PHONE
          # If set, only private devices will be queried.
          private: false
artifacts:
  download:
    when: always
    match:
      - "*.junit.xml"
    directory: ./artifacts/
